### ISSUE TITLE
CDI-Unit is incompatible with DeltaSpike 1.7.0

### ISSUE THREAD

**Issue by johannesschaefer** [cdi-unit/cdi-unit#100]
When using CDI-Unit (3.1.4) together with DeltaSpike 1.7.0 and later the following exection is thrown when executing the cdi-unit/deltaspike test case ( https://github.com/BrynCooke/cdi-unit/tree/master/cdi-unit/src/test/java/org/jglue/cdiunit/deltaspike ). Using DeltaSpike 1.6.1 everything is ok.

```
java.lang.IllegalStateException: Could not find beans for Type=class org.apache.deltaspike.proxy.impl.invocation.InterceptorLookup and qualifiers:[]
	at org.apache.deltaspike.core.api.provider.BeanProvider.getContextualReference(BeanProvider.java:154)
	at org.apache.deltaspike.core.api.provider.BeanProvider.getContextualReference(BeanProvider.java:121)
	at org.apache.deltaspike.core.api.provider.BeanProvider.getContextualReference(BeanProvider.java:100)
	at org.apache.deltaspike.proxy.impl.invocation.AbstractManualInvocationHandler.init(AbstractManualInvocationHandler.java:94)
	at org.apache.deltaspike.proxy.impl.invocation.AbstractManualInvocationHandler.lazyInit(AbstractManualInvocationHandler.java:83)
	at org.apache.deltaspike.proxy.impl.invocation.AbstractManualInvocationHandler.invoke(AbstractManualInvocationHandler.java:37)
	at org.apache.deltaspike.proxy.impl.invocation.DelegateManualInvocationHandler.staticInvoke(DelegateManualInvocationHandler.java:39)
	at cdi.TestEntityRepository$$DSPartialBeanProxy.save(Unknown Source)
	at cdi.TestDeltaspikeTransactions.test(TestDeltaspikeTransactions.java:52)
	at cdi.TestDeltaspikeTransactions$Proxy$_$$_WeldSubclass.test$$super(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:49)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
	at org.apache.deltaspike.jpa.impl.transaction.ResourceLocalTransactionStrategy.execute(ResourceLocalTransactionStrategy.java:133)
	at org.apache.deltaspike.jpa.impl.transaction.TransactionalInterceptor.executeInTransaction(TransactionalInterceptor.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:74)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at cdi.TestDeltaspikeTransactions$Proxy$_$$_WeldSubclass.test(Unknown Source)
	at cdi.TestDeltaspikeTransactions$Proxy$_$$_WeldClientProxy.test(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.jglue.cdiunit.CdiRunner$2.evaluate(CdiRunner.java:181)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by ikysil** [comment]
Changes required to support newer versions of DeltaSpike in `SupportDeltaspikeData`

For DeltaSpike 1.7.x and 1.8.x add:
```java
@AdditionalClasspaths({RepositoryExtension.class, InterceptorLookup.class})
```

For DeltaSpike 1.9.x add:
```java
@AdditionalClasspaths({RepositoryExtension.class, DeltaSpikeProxyInvocationHandler.class})
```

Also, in the test `TestDeltaspikeTransactions`
```java
	@Produces
//	@RequestScoped -- this scope is not active yet when DeltaSpike builds the repository implementation
	protected EntityManager createEntityManager() {
		return emf.createEntityManager();
	}
```

The changes to support the newer versions of the DeltaSpike are not backward compatible.
Need to clarify the usage per version.
