### ISSUE TITLE
Unable to run cdiunit on Zulu JDK 11

### ISSUE THREAD

**Issue by vferries** [cdi-unit/cdi-unit#182]
When trying to run cdinuit (version 4.1.0) with Java 11 Zulu JDK, I get the following exception :

> cannot connect to jrt:/org.openjsse
java.io.IOException: cannot connect to jrt:/org.openjsse
	at java.base/sun.net.www.protocol.jrt.JavaRuntimeURLConnection.connect(JavaRuntimeURLConnection.java:129)
	at java.base/sun.net.www.protocol.jrt.JavaRuntimeURLConnection.getInputStream(JavaRuntimeURLConnection.java:140)
	at java.base/java.net.URL.openStream(URL.java:1140)
	at org.jglue.cdiunit.internal.WeldTestUrlDeployment.getEntriesFromManifestClasspath(WeldTestUrlDeployment.java:429)
	at org.jglue.cdiunit.internal.WeldTestUrlDeployment.populateCdiClasspathSet(WeldTestUrlDeployment.java:387)
	at org.jglue.cdiunit.internal.WeldTestUrlDeployment.<init>(WeldTestUrlDeployment.java:97)
	at org.jglue.cdiunit.internal.Weld11TestUrlDeployment.<init>(Weld11TestUrlDeployment.java:28)
	at org.jglue.cdiunit.CdiRunner$1.createDeployment(CdiRunner.java:107)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:777)
	at org.jglue.cdiunit.CdiRunner.createTest(CdiRunner.java:129)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.jglue.cdiunit.CdiRunner.methodBlock(CdiRunner.java:179)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)

The problem is that Zulu includes openjsse as a module and the ClassGraphScanner tries to resolve it. That is not the case with the other JDK 11 releases (like OpenJDK).

One way could be to simply blacklist that module with the blacklistModules(String...) method in the ClassGraph class called from the getClasspathURLs method in the ClassGraphScanner class. But nothing is exposed to configure cdiunit to do that.

Do you have any idea how to solve that issue and be able to run my code while migrating to Zulu 11 ?
Thanks in advance.

**Comment by ikysil** [comment]
The build for cdi-unit is failing with Java 11 Zulu JDK.

```
initializeCdi(org.jglue.cdiunit.TestNgCdiRunner)  Time elapsed: 1.729 sec  <<< FAILURE!
java.lang.RuntimeException: java.io.IOException: cannot connect to jrt:/org.openjsse
Caused by: java.io.IOException: cannot connect to jrt:/org.openjsse
```

**Comment by ikysil** [comment]
Dear Vincent (@vferries),

Could you please check with the cdi-unit built from the master branch?

**Comment by vferries** [comment]
Hi Illya,

I've seen your changes and think they will solve my issue. I cannot test
today but will do that soon.
I have temporarily bypassed by patching cdi-unit and excluding just the
jsse module, but excluding all modules will work (as long as we do not use
modules in our project).

I patched the ClassGraphScanner and not the CachingClassGraphScanner, so I
will have to check again.

Thanks.

Le mer. 19 août 2020 à 09:17, Illya Kysil <notifications@github.com> a
écrit :

**Comment by dirkey** [comment]
I still get an error when running CDI Unit under Zulu:
java.io.IOException: cannot connect to jrt:/com.azul.crs.client
